#ifndef _CONSTANTS_H
#define _CONSTANTS_H
#define FRONT_CAMERA_CODE '0'
#define BRAKE_BY_WIRE_CODE '1'
#define THROTTLE_CONTROL_CODE '2'
#define HALT_CODE '3'
#define DEFAULT_PROTOCOL 0
#define HUMAN_INTERFACE_PORT 1025
#define UDP_CENECU_PORT 1026
#define MAXLINE 1024
#endif